kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: myclaim
  annotations:
    os: "windows"
spec:
  storageClassName: "iscsi-targetd-vg-targetd"
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi

